[project]
name = "embedded-systems-capstone-final-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gpiozero>=2.0.1",
    "google-genai>=1.0.0",
    "imageio-ffmpeg>=0.6.0",
    "opencv-python-headless>=4.10.0.84",
    "pygame-ce>=2.5.7",
    "rpi-gpio>=0.7.1",
    "rpi-ws281x>=5.0.0",
]

[project.scripts]
preprocess-timeline = "preprocess.cli:main"
run-timeline = "main:main"
